### ISSUE TITLE
Feature request: bidirectional dshot

### ISSUE THREAD

**Issue by mxxmxn** [Guppy16/pico-dshot#4]
First of all, thank you for your great work in this repo.

I would be interested in using bidirectional dshot because I need the frequent erpm values.
Have you already looked into this?

**Comment by Guppy16** [comment]
Hey! Sorry for the late reply / thanks for your interest. Unfortunately, I haven't implemented bidirectional dshot (yet). I don't have much time at the moment to work on this feature; the earliest I can star working on this is mid Jan. Nevertheless, I would be happy to assist you if you would like to work on this?

**Comment by mxxmxn** [comment]
@simonwunderlich implemented bidirectional dshot using pio: https://github.com/simonwunderlich/pio-dshot
